apiVersion: apps/v1
kind: Deployment
metadata:
    name: probely-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probely-agent
  template:
    metadata:
      labels:
        app: probely-agent
    spec:
      initContainers:
      - name: init
        image: busybox:stable
        command:
        - sh
        - -c
        - sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.forwarding=1
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
      containers:
      - name: agent
        privileged: true
        image: probely/farcaster-onprem-agent:v2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: farcaster-secrets
          mountPath: /secrets/farcaster/data
          readOnly: true
        - name: host-tun-dev
          mountPath: /dev/net/tun
      volumes:
      - name: farcaster-secrets
        projected:
          sources:
          - secret:
              name: farcaster-tunnel-secrets
          - secret:
              name: farcaster-gateway-secrets
      - name: host-tun-dev
        hostPath:
          path: /dev/net/tun
          type: CharDevice
      terminationGracePeriodSeconds: 3
  minReadySeconds: 2
