apiVersion: apps/v1
kind: Deployment
metadata:
    name: farcaster-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farcaster-agent
  template:
    metadata:
      labels:
        app: farcaster-agent
    spec:
      containers:
      - name: agent
        privileged: true
        image: probely/farcaster-onprem-agent:v3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: farcaster-secrets
          mountPath: /secrets/farcaster/data
          readOnly: true
        - name: host-tun-dev
          mountPath: /dev/net/tun
      volumes:
      - name: farcaster-secrets
        projected:
          sources:
          - secret:
              name: farcaster-tunnel-secrets
          - secret:
              name: farcaster-gateway-secrets
      terminationGracePeriodSeconds: 3
  minReadySeconds: 2
