FROM debian:buster-slim

COPY . /build
WORKDIR /build

ARG VERSION

ENV GOLANG_VERSION 1.22.3
ENV GOLANG_HASH "8920ea521bad8f6b7bc377b4824982e011c19af27df88a815e3586ea895f1b36"
ENV GOPATH /go

RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        make \
        ca-certificates \
        curl \
    && rm -rf /var/lib/apt/lists/* \
    && outfile="go.tar.gz" \
    && curl -Lo ${outfile} "https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz" \
    && echo "${GOLANG_HASH}  ${outfile}" | sha256sum -c - \
    && tar -C /usr/local -xzf ${outfile} \
    && rm ${outfile} \
    && export PATH="/usr/local/go/bin:$PATH" \
    && mkdir -p ${GOPATH}/src ${GOPATH}/bin \
    go version

ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN set -eux \
    && make linux
