FROM golang:1.26-bookworm

COPY . /build
WORKDIR /build

ARG VERSION

RUN set -eux \
    && apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y --no-install-recommends \
        make \
        ca-certificates \
    && make linux
