version: '3.3'

services:
  agent:
    image: {{DOCKER_IMAGE}}
    container_name: probely-agent
    stop_grace_period: 1s
    environment:
    - HTTP_PROXY
    volumes:
    - {{SECRETS_PATH}}:/secrets/farcaster/data:z,ro
    devices:
    - /dev/net/tun:/dev/net/tun
    tmpfs:
    - /run
    cap_add:
    - NET_ADMIN
    restart: unless-stopped
