version: '3.3'

services:
  agent:
    image: probely/farcaster-onprem-agent:v3
    container_name: probely-agent
    stop_grace_period: 1s
    # Environment variables for the Agent to work:
    #
    #   FARCASTER_AGENT_TOKEN
    #   The Agent's token is obtained when creating a Scanning Agent in the Probely app.
    #   Learn more at https://help.probely.com/en/articles/6503388-how-to-install-a-scanning-agent
    #
    #   FARCASTER_API_URL
    #   Probely's API URL. If not set, the Agent will use the API URLs for all regions.
    #
    #   FARCASTER_FORCE_TCP
    #   If set to true, the Agent will use TCP to connect to Snyk.
    #
    #   FARCASTER_PROXY_NAMES
    #   If set to true, the Agent will use hostnames in proxy requests when available.
    #
    #   HTTP_PROXY (optional)
    #   An advanced option that can be used to configure an HTTP proxy for the Agent to connect to Probely.
    #
    environment:
    - FARCASTER_AGENT_TOKEN
    - FARCASTER_API_URL
    - HTTP_PROXY
    - FARCASTER_FORCE_TCP
    - FARCASTER_PROXY_NAMES
    tmpfs:
    - /run
    cap_add:
      # Required for WireGuard kernel support. If you remove this, the Agent will fall back to a userspace TCP/IP stack.
      - NET_ADMIN
    restart: unless-stopped

volumes:
  secrets:
