version: '3.3'

services:
  agent:
    image: probely/farcaster-onprem-agent:v3
    container_name: probely-agent
    stop_grace_period: 1s
    # Environment variables for the Agent to work:
    #
    #   FARCASTER_AGENT_TOKEN
    #   The Agent's token is obtained when creating a Scanning Agent in the Probely app.
    #   Learn more at https://help.probely.com/en/articles/6503388-how-to-install-a-scanning-agent
    #
    #   FARCASTER_API_URL
    #   Probely's API URL
    #
    #   HTTP_PROXY (optional)
    #   An advanced option that can be used to configure an HTTP proxy for the Agent to connect to Probely.
    #
    environment:
    - FARCASTER_AGENT_TOKEN
    - FARCASTER_API_URL
    - HTTP_PROXY
    - FARCASTER_FORCE_TCP
    tmpfs:
    - /run
    cap_add:
    - NET_ADMIN
    restart: unless-stopped

volumes:
  secrets:
