// This file was auto-generated by "make version". Do not change it directly!

package settings

// Version and Commit are injected at build time via linker flags.
var (
	// Version holds the semantic version of the build (e.g. "1.2.3").
	Version string = "dev"

	// Commit is the short git commit hash corresponding to this build.
	Commit string = "none"
)
